public class GodManyMethods {
  public Integer x;

  public void m1(){ System.debug(1); }
  public void m2(){ System.debug(2); }
  public void m3(){ System.debug(3); }
  public void m4(){ System.debug(4); }
  public void m5(){ System.debug(5); }
  public void m6(){ System.debug(6); }
  public void m7(){ System.debug(7); }
  public void m8(){ System.debug(8); }
  public void m9(){ System.debug(9); }
  public void m10(){ System.debug(10); }
  public void m11(){ System.debug(11); }
  public void m12(){ System.debug(12); }
  public void m13(){ System.debug(13); }
  public void m14(){ System.debug(14); }
  public void m15(){ System.debug(15); }
  public void m16(){ System.debug(16); }
}
