public class TooLong {

  public void longMethod() {
    Integer i = 0;
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
    System.debug(i);
  }
  
}
